### ISSUE TITLE
笔刷强度调整-显示bug

### ISSUE THREAD

**Issue by xz-blender** [atticus-lv/PolyQuilt#2]
当使用快捷键调整笔刷强度时，靠近最大值边缘附近徘徊会导致该半径持续扩大

**Comment by xz-blender** [comment]
![Uploading Honeycam 2023-12-31 17-51-19.gif…]()

**Comment by xz-blender** [comment]
<img width="248" alt="Snipaste_2023-12-31_17-55-47" src="https://github.com/atticus-lv/PolyQuilt/assets/53850249/44e96511-b40e-4eb9-b1fd-6ae21e2f0d61">

**Comment by xz-blender** [comment]
![Honeycam 2023-12-31 17-51-19](https://github.com/atticus-lv/PolyQuilt/assets/53850249/f76de346-9a7f-470c-af98-b9feb73758da)

**Comment by atticus-lv** [comment]
操作并不是垂直滑动的，而是逐渐往右的滑动（并且在变慢），应该是判定精度太高了，可以尝试下修改。快速滑动的话应该会有所改善

**Comment by atticus-lv** [comment]
现在应该有所改善，添加了小幅度移动和添加方向判定的检测 0213591
可以下载最新的试试

**Comment by xz-blender** [comment]
感谢修复！
:D
